# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sprout < Formula
  desc "Git worktree manager with terminal UI and tmux workflows."
  homepage "https://github.com/joegrabski/sprout"
  version "0.1.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.9/sprout_0.1.9_darwin_amd64.tar.gz"
      sha256 "9b786de68570fecd807a6f2156d6e494fc3c4fed735df006cfefb0781afab560"

      define_method(:install) do
        bin.install "sprout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.9/sprout_0.1.9_darwin_arm64.tar.gz"
      sha256 "6a75a91c207b9108dfd4a831397064ef6f57d98a6cb64a6309f36eb10ed1e1de"

      define_method(:install) do
        bin.install "sprout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.9/sprout_0.1.9_linux_amd64.tar.gz"
      sha256 "0ced459122a3fe945d7ae0188f649e6100de3013b26c3478f1a9dc6a191f5946"
      define_method(:install) do
        bin.install "sprout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.9/sprout_0.1.9_linux_arm64.tar.gz"
      sha256 "145c496bbbfc1776f175a90ea997033ef6b2eaf7a0343adb8d88246db8fec6d9"
      define_method(:install) do
        bin.install "sprout"
      end
    end
  end

  test do
    system "#{bin}/sprout", "version"
  end
end
