# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sprout < Formula
  desc "Git worktree manager with terminal UI and tmux workflows."
  homepage "https://github.com/joegrabski/sprout"
  version "0.1.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.8/sprout_0.1.8_darwin_amd64.tar.gz"
      sha256 "97f546cb3e7036e64ec3e55f8c259a9eb0951d597ed226f631f1f7c4943e87bd"

      define_method(:install) do
        bin.install "sprout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.8/sprout_0.1.8_darwin_arm64.tar.gz"
      sha256 "42cee18dff1b217c077795d4ba635eb595bc19d14b711f2f29f1e4839716e5e1"

      define_method(:install) do
        bin.install "sprout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.8/sprout_0.1.8_linux_amd64.tar.gz"
      sha256 "582567ed7b8bf994736996352f20bde4b829b54b3f790afce1a311c6cea4ae4c"
      define_method(:install) do
        bin.install "sprout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.8/sprout_0.1.8_linux_arm64.tar.gz"
      sha256 "54810e4d174b81520199ca8cc38aa0f42e164d305fd1a5ba08e1cb3483558494"
      define_method(:install) do
        bin.install "sprout"
      end
    end
  end

  test do
    system "#{bin}/sprout", "version"
  end
end
