# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sprout < Formula
  desc "Git worktree manager with terminal UI and tmux workflows."
  homepage "https://github.com/joegrabski/sprout"
  version "0.1.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.11/sprout_0.1.11_darwin_amd64.tar.gz"
      sha256 "d9eae48cfa1387aabf8bbb558a340539599f95b7958b09f002f83396200d08a0"

      define_method(:install) do
        bin.install "sprout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.11/sprout_0.1.11_darwin_arm64.tar.gz"
      sha256 "a84b77df64c06c605ea872f0c0c411fad7fe964edf61a27f2bd1104faec89e44"

      define_method(:install) do
        bin.install "sprout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.11/sprout_0.1.11_linux_amd64.tar.gz"
      sha256 "e5df881bbb8de872f7b2d767bfe379b152e9ba0028ac10589e9735221f6e184b"
      define_method(:install) do
        bin.install "sprout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joegrabski/sprout/releases/download/v0.1.11/sprout_0.1.11_linux_arm64.tar.gz"
      sha256 "3dfe45e4c7e24cea2720fa142b01ff34b992a3317e919698b3a5db9712a70f1b"
      define_method(:install) do
        bin.install "sprout"
      end
    end
  end

  test do
    system "#{bin}/sprout", "version"
  end
end
